name = "FiveBarLinkage"
uuid = "277534b0-d1bf-4510-bcf3-a2034bf3b560"
authors = ["Herschmann, Sam <sam.herschmann@ukaea.uk>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
DifferentialEquations = "7.15.0"
Plots = "1.40.9"
Symbolics = "6.22.1"
