name = "FiveBarLinkage"
uuid = "277534b0-d1bf-4510-bcf3-a2034bf3b560"
authors = ["Herschmann, Sam <sam.herschmann@ukaea.uk>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
DelimitedFiles = "1.9.1"
DifferentialEquations = "7.15.0"
Interpolations = "0.15.1"
LinearAlgebra = "1.11.0"
Plots = "1.40.9"
Symbolics = "6.22.1"
